### PR TITLE
Documentation update - SBB code examples - response event handling

### PR DESCRIPTION
**Pull request by tzieleniewski**
References: #7 
Updated documentation SBB code examples with information about 'empty' HTTP response event processing.
Updated POM files formatting.

### CODE REVIEW

**Comment by tzieleniewski** [comment]
References as well #9 (HTTP Servlet RA - default HTTP response status change).

**Comment by SergeyLee** [comment]
Hi Tomasz!
I'll review your PR today.
But in future please divide changes on several commits. One commit on changes formatting. Other commits on main changes.

Best regards
Sergey Lee

**Comment by SergeyLee** [comment]
I tried to build project: mvn clean install, and I have errors:

> [ERROR] /home/sergeypovarnin/Projects/MobiusRepo/jain-slee.http/resources/http-client-nio/ra/src/main/java/org/mobicents/slee/ra/httpclient/nio/ra/HttpClientNIOResourceAdaptor.java:[123,22] error: cannot find symbol
> [ERROR]  variable httpclient of type HttpAsyncClient
> /home/sergeypovarnin/Projects/MobiusRepo/jain-slee.http/resources/http-client-nio/ra/src/main/java/org/mobicents/slee/ra/httpclient/nio/ra/HttpClientNIOResourceAdaptor.java:[153,27] error: cannot find symbol
> [ERROR]  variable httpclient of type HttpAsyncClient
> /home/sergeypovarnin/Projects/MobiusRepo/jain-slee.http/resources/http-client-nio/ra/src/main/java/org/mobicents/slee/ra/httpclient/nio/ra/HttpClientNIOResourceAdaptorSbbInterfaceImpl.java:[41,22] error: cannot find symbol
> [INFO] 3 errors

If I build project without your changes it builds successful.
Now I am investigating what is wrong in pom.xml changed by you.

**Comment by SergeyLee** [comment]
Ok. I found reason: in parent pom.xml you fixed version for httpasyncclient from 4.0-beta3 to 4.0.

**Comment by SergeyLee** [comment]
I decided to leave httpasyncclient 4.0-beta3 for now.
But I will create issue for updating httpasyncclient to 4.0 or higher version.

**Pull request closed without merging**
